"""ticket table

Revision ID: fcc32539e9b2
Revises: 42f99f4ce006
Create Date: 2019-09-09 11:03:01.517438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc32539e9b2'
down_revision = '42f99f4ce006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('o365', sa.String(length=400), nullable=True),
    sa.Column('assigned_to', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
